name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.15.6'
        otp-version: '26.0.2'

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Check formatting
      run: mix format --check-formatted

    - name: Run credo
      run: mix credo --strict

    - name: Run dialyzer
      run: |
        mix dialyzer --halt-exit-status

    - name: Run tests
      env:
        MIX_ENV: test
      run: mix test 